version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${{ secrets.DOCKER_USERNAME }}/style-sync-selector-backend:latest
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${{ secrets.DOCKER_USERNAME }}/style-sync-selector-frontend:latest
    ports:
      - "8080:8080"
    environment:
      - VITE_BACKEND_URL=http://backend:8000
    depends_on:
      - backend
